sudo: required
services: 
 - docker
 
before_install:
 - docker build -t noneedrelax/docker-react -f Dockerfile.dev . 
 
script:
 - docker run noneedrelax/docker-react npm run test -- --coverage
 
after_success:
 - pip install --user awscli 
 - export PATH=$PATH:$HOME/.local/bin 
 - eval $(aws ecr get-login --region us-west-2) 
 - docker build -t noneedrelax/docker-react .
 - docker tag noneedrelax/docker-react:latest "$REGISTRY_ID"/frontend:latest
 - docker push "$REGISTRY_ID"/frontend:latest
  
